if(sessionStorage.getItem('websitename-admin-access')!=='1')window.location.replace('index.html');

const FAQ_KEY='websitename-faqs';
const BLOG_KEY='websitename-blogs';
let language='ar';
const read=(key)=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}};
const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const formData=form=>Object.fromEntries(new FormData(form).entries());
const notice=document.querySelector('#adminNotice');
const t=(en,ar)=>language==='ar'?ar:en;

function notify(message){notice.textContent=message;window.setTimeout(()=>{notice.textContent=''},3500)}
function renderSaved(){const faqs=read(FAQ_KEY),blogs=read(BLOG_KEY);document.querySelector('#faqCount').textContent=faqs.length;document.querySelector('#blogCount').textContent=blogs.length;renderList('#savedFaqs',faqs,'faq');renderList('#savedBlogs',blogs,'blog')}
function renderList(selector,items,type){const root=document.querySelector(selector);root.replaceChildren();if(!items.length){const empty=document.createElement('div');empty.className='saved-empty';empty.textContent=t('Nothing added yet.','لا توجد إضافات حتى الآن.');root.append(empty);return}items.forEach(item=>{const row=document.createElement('div');row.className='saved-item';const title=document.createElement('span');title.className='saved-item-title';title.textContent=language==='ar'?(item.titleAr||item.title):(item.title||item.titleAr);const remove=document.createElement('button');remove.type='button';remove.className='delete-item';remove.dataset.type=type;remove.dataset.id=item.id;remove.textContent=t('Delete','حذف');row.append(title,remove);root.append(row)})}

function openEditorPanel(name){const tab=[...document.querySelectorAll('.editor-tab')].find(item=>item.dataset.panel===name);const panel=document.querySelector(`[data-panel-content="${name}"]`);if(!tab||!panel)return;document.querySelectorAll('.editor-tab').forEach(item=>{const active=item===tab;item.classList.toggle('active',active);item.setAttribute('aria-selected',String(active))});document.querySelectorAll('[data-panel-content]').forEach(item=>{item.hidden=item!==panel});panel.querySelector('input,textarea')?.focus({preventScroll:true})}
document.querySelectorAll('.editor-tab').forEach(tab=>tab.addEventListener('click',event=>{event.preventDefault();openEditorPanel(tab.dataset.panel)}));
document.querySelector('#faqForm').addEventListener('submit',event=>{event.preventDefault();const data=formData(event.currentTarget);const item={id:`faq-${Date.now()}`,title:data.title.trim(),titleAr:data.titleAr.trim(),tags:data.tags.trim(),tagsAr:data.tagsAr.trim(),icon:'',tint:'#eee6f8',color:'#9675ba',replies:[[data.prompt.trim(),data.answer.trim()]],repliesAr:[[data.promptAr.trim(),data.answerAr.trim()]]};write(FAQ_KEY,[...read(FAQ_KEY),item]);event.currentTarget.reset();renderSaved();notify(t('FAQ published on this browser.','نُشر السؤال على هذا المتصفح.'))});
document.querySelector('#blogForm').addEventListener('submit',event=>{event.preventDefault();const data=formData(event.currentTarget);const item={id:`blog-${Date.now()}`,title:data.title.trim(),titleAr:data.titleAr.trim(),category:data.category.trim(),categoryAr:data.categoryAr.trim(),author:data.author.trim(),authorAr:data.authorAr.trim(),desc:data.desc.trim(),descAr:data.descAr.trim(),body:data.body.trim(),bodyAr:data.bodyAr.trim(),time:t('NEW ARTICLE','مقال جديد'),palette:'lilac',art:'tooth'};write(BLOG_KEY,[...read(BLOG_KEY),item]);event.currentTarget.reset();renderSaved();notify(t('Blog published on this browser.','نُشر المقال على هذا المتصفح.'))});

document.querySelector('.saved-card').addEventListener('click',event=>{const button=event.target.closest('.delete-item');if(!button)return;const key=button.dataset.type==='faq'?FAQ_KEY:BLOG_KEY;write(key,read(key).filter(item=>item.id!==button.dataset.id));renderSaved();notify(t('Entry deleted.','تم حذف المحتوى.'))});
document.querySelector('#refreshList').addEventListener('click',renderSaved);
document.querySelector('#adminLanguage').addEventListener('click',()=>{language=language==='ar'?'en':'ar';applyLanguage()});
function applyLanguage(){const arabic=language==='ar';document.documentElement.lang=language;document.documentElement.dir=arabic?'rtl':'ltr';document.querySelectorAll('[data-en][data-ar]').forEach(node=>{node.textContent=arabic?node.dataset.ar:node.dataset.en});document.querySelector('#adminLanguage').textContent=arabic?'English':'العربية';document.querySelectorAll('input[name],textarea[name]').forEach(field=>{const arabicPlaceholders={title:'اكتب العنوان بالإنجليزية',titleAr:'اكتب العنوان بالعربية',tags:'مثال: الأسنان، التفريش',tagsAr:'مثال: الأسنان، التفريش',prompt:'اكتب رسالة مقترحة بالإنجليزية',answer:'اكتب الإجابة بالإنجليزية',promptAr:'اكتب رسالة مقترحة بالعربية',answerAr:'اكتب الإجابة بالعربية',author:'اسم الطبيب بالإنجليزية',authorAr:'اسم الطبيب بالعربية',category:'مثال: صحة اللثة',categoryAr:'مثال: صحة اللثة',desc:'اكتب ملخصًا قصيرًا',descAr:'اكتب ملخصًا قصيرًا بالعربية',body:'اكتب المقال كاملًا',bodyAr:'اكتب المقال كاملًا بالعربية'};const englishPlaceholders={title:'Write the title in English',titleAr:'Write the title in Arabic',tags:'Example: teeth, brushing',tagsAr:'Example: teeth, brushing',prompt:'Write a suggested patient message',answer:'Write the answer in English',promptAr:'Write a suggested patient message in Arabic',answerAr:'Write the answer in Arabic',author:'Doctor’s name in English',authorAr:'Doctor’s name in Arabic',category:'Example: Gum health',categoryAr:'Example: Gum health',desc:'Write a short summary',descAr:'Write a short Arabic summary',body:'Write the full article',bodyAr:'Write the full article in Arabic'};const placeholders=arabic?arabicPlaceholders:englishPlaceholders;if(placeholders[field.name])field.placeholder=placeholders[field.name]});renderSaved()}
renderSaved();applyLanguage();
