const faqs = [
  { id:'brush', icon:'01', tint:'#eee6f8', color:'#9675ba', title:'Am I brushing my teeth the right way?', tags:'brushing brush technique teeth toothbrush', replies:[['How long should I brush?','Two minutes is a good goal. Try giving each part of your mouth about 30 seconds, and use gentle, small circular movements along the gumline.'],['Do I need a special toothbrush?','A soft-bristled toothbrush works well for most people. What matters most is brushing gently and replacing your brush every three to four months, or sooner if the bristles look worn.'],['Should I brush before or after breakfast?','Either routine can work. If you brush after eating, especially after acidic foods or drinks, waiting around 30 minutes gives your enamel time to recover.']]},
  { id:'sensitive', icon:'02', tint:'#f9e8ed', color:'#c584a0', title:'Why are my teeth suddenly sensitive?', tags:'sensitive sensitivity cold hot pain teeth', replies:[['What can make teeth sensitive?','Sensitivity can have a few causes, including worn enamel, gum changes, or a cavity. A dentist can help work out what’s behind yours, especially if it’s new or persistent.'],['Can I keep drinking cold drinks?','You can try avoiding what triggers the sensitivity for now and use a soft brush with gentle pressure. If it continues, check in with your dentist so they can take a closer look.'],['When should I see a dentist?','Book a dental visit if sensitivity is new, getting worse, focused on one tooth, or lingering after the trigger is gone. A dentist can recommend the right next step.']]},
  { id:'floss', icon:'03', tint:'#e9effa', color:'#718eb7', title:'Do I really need to floss every day?', tags:'floss flossing between teeth clean', replies:[['What if flossing makes my gums bleed?','A little bleeding can happen when gums are irritated, but it should improve with gentle, regular cleaning. If bleeding continues or is heavy, ask your dentist for advice.'],['Are interdental brushes okay instead?','Yes, interdental brushes can be a helpful way to clean between teeth. A dentist can help you choose the right size so the brush fits comfortably.'],['When should I floss?','Choose a time you can stick to each day. Cleaning between teeth before brushing can make it easier to follow with brushing, but a consistent routine is what counts.']]},
  { id:'gums', icon:'04', tint:'#f9ebdf', color:'#c38d68', title:'How do I know if my gums are healthy?', tags:'gums gum bleeding swollen health', replies:[['What do healthy gums look like?','Healthy gums are often firm and don’t bleed easily. Everyone’s natural gum color is different, so pay attention to changes in your own mouth.'],['My gums look a little swollen. What now?','Try gentle brushing and cleaning between your teeth. Swelling that lasts, gets worse, or comes with pain is a good reason to see your dentist.'],['When is gum bleeding a concern?','If bleeding keeps happening despite gentle daily cleaning, or comes with swelling or discomfort, arrange a dental visit to get personalized advice.']]},
  { id:'breath', icon:'05', tint:'#e8f1eb', color:'#71967c', title:'What can I do about bad breath?', tags:'breath bad breath mouth smell halitosis', replies:[['Does brushing my tongue help?','Gently cleaning your tongue can help remove buildup. Brush twice daily, clean between your teeth, and drink water regularly as part of your routine.'],['Could dry mouth be related?','A dry mouth can contribute to breath changes. Water may help, but if it persists or comes with other symptoms, ask a dental professional what could be causing it.'],['When should I ask my dentist?','If bad breath continues even with a steady brushing and flossing routine, a dentist can check for dental causes and talk through possible next steps.']]},
  { id:'whitening', icon:'06', tint:'#f8eaf2', color:'#bf7ea0', title:'Is teeth whitening safe for everyone?', tags:'whitening whiten teeth bleaching safe', replies:[['Should I try whitening products?','Whitening isn’t suitable for everyone, and products can cause temporary sensitivity. It’s best to ask a dentist before starting, especially if you have dental work or existing sensitivity.'],['Can whitening damage my teeth?','Some products can irritate gums or make teeth feel sensitive. Follow product directions carefully and speak with a dentist about options that suit your teeth.'],['Will whitening work on crowns or fillings?','Whitening products may not change the color of crowns, fillings, or veneers. A dentist can explain what results to expect for your smile.']]}
];
faqs.push(...JSON.parse(localStorage.getItem('websitename-faqs')||'[]'));
const blogs=[
  {category:'EVERYDAY CARE',time:'5 MIN READ',title:'The tiny daily habits that make a big difference',desc:'A kinder, simpler approach to building a routine your smile will thank you for.',palette:'lilac',art:'tooth'},
  {category:'GUM HEALTH',time:'4 MIN READ',title:'Let’s talk about your gums',desc:'What your gums might be telling you, and how to give them a little extra care.',palette:'peach',art:'flower'},
  {category:'SMILE NOTES',time:'6 MIN READ',title:'Myth or fact: your smile edition',desc:'A few common dental beliefs, gently unpacked with a professional perspective.',palette:'rose',art:'smile'}
];
blogs.push(...JSON.parse(localStorage.getItem('websitename-blogs')||'[]'));
const people=['Dr. Ziad Mahmoud','Dr. Omar Sameh','Dr. Yehia Tarek','Dr. Tarek Mohammed','Dr. Shreef Mohammed','Dr. Ranim Elhusseiny','Dr. Sara Mohammad','Dr. Nada Waleed','Dr. Nadine Ahmed','Dr. Najah Abdelfattah','Eng. Mohamed Ahmed'];
const peopleAr=['د. زياد محمود','د. عمر سامح','د. يحيى طارق','د. طارق محمد','د. شريف محمد','د. رنيم الحسيني','د. سارة محمد','د. ندى وليد','د. نادين أحمد','د. نجاح عبد الفتاح','م. محمد أحمد'];
const peoplePhotoFiles=[1,2,3,4,6,10,7,8,9,11,12];
const cofounders=[{name:'Prof. Dalia Ghalwash',nameAr:'أ.د. داليا غلاوش',photo:'0.png'},{name:'Dr. Youssef Yasser',nameAr:'د. يوسف ياسر',photo:'5.png'}];
let currentLang='ar';
const faqAr={
  brush:{title:'هل أفرّش أسناني بالطريقة الصحيحة؟',tags:'تفريش تنظيف فرشاة الأسنان',replies:[['كم من الوقت يجب أن أفرّش أسناني؟','دقيقتان مدة مناسبة. خصّص نحو 30 ثانية لكل جزء من فمك، واستخدم حركات دائرية لطيفة بمحاذاة اللثة.'],['هل أحتاج إلى فرشاة أسنان خاصة؟','تناسب الفرشاة ناعمة الشعيرات معظم الأشخاص. الأهم هو التفريش بلطف وتغيير الفرشاة كل ثلاثة أو أربعة أشهر، أو عندما تتآكل شعيراتها.'],['هل أفرّش أسناني قبل الإفطار أم بعده؟','يمكنك اتباع ما يناسب روتينك. إذا فرّشت بعد تناول أطعمة أو مشروبات حمضية، فانتظر نحو 30 دقيقة حتى يتعافى مينا الأسنان.']]},
  sensitive:{title:'لماذا أصبحت أسناني حساسة فجأة؟',tags:'حساسية الأسنان ألم بارد ساخن',replies:[['ما أسباب حساسية الأسنان؟','قد تنتج الحساسية عن تآكل المينا أو تغيّر اللثة أو التسوس. يستطيع طبيب الأسنان مساعدتك في معرفة السبب، خصوصًا إذا كانت الحساسية جديدة أو مستمرة.'],['هل يمكنني الاستمرار في شرب المشروبات الباردة؟','حاول مؤقتًا تجنب ما يسبب الحساسية واستخدم فرشاة ناعمة بضغط لطيف. إذا استمرت، استشر طبيب أسنانك.'],['متى يجب أن أزور طبيب الأسنان؟','احجز موعدًا إذا كانت الحساسية جديدة أو تزداد أو تتركز في سن واحدة أو تستمر بعد زوال السبب.']]},
  floss:{title:'هل أحتاج فعلًا إلى استخدام الخيط يوميًا؟',tags:'خيط تنظيف الأسنان بين الأسنان',replies:[['ماذا لو نزفت لثتي عند استخدام الخيط؟','قد يحدث نزيف بسيط عندما تكون اللثة متهيجة، لكن ينبغي أن يتحسن مع التنظيف المنتظم واللطيف. إذا استمر النزيف أو كان شديدًا، استشر طبيب الأسنان.'],['هل يمكنني استخدام الفرشاة بين الأسنان بدلًا منه؟','نعم، قد تساعد الفرشاة المخصصة للتنظيف بين الأسنان. يمكن لطبيب الأسنان مساعدتك في اختيار المقاس المناسب.'],['متى أستخدم خيط الأسنان؟','اختر وقتًا يسهل عليك الالتزام به يوميًا. تنظيف ما بين الأسنان قبل التفريش قد يساعدك على إكمال روتينك.']]},
  gums:{title:'كيف أعرف أن لثتي بصحة جيدة؟',tags:'اللثة نزيف تورم صحة',replies:[['كيف تبدو اللثة الصحية؟','غالبًا ما تكون اللثة الصحية متماسكة ولا تنزف بسهولة. يختلف لون اللثة الطبيعي من شخص لآخر؛ انتبه للتغيّرات التي تطرأ عليك.'],['تبدو لثتي متورمة قليلًا، ماذا أفعل؟','حاول التفريش بلطف والتنظيف بين أسنانك. إذا استمر التورم أو ازداد أو صاحبه ألم، فاستشر طبيب الأسنان.'],['متى يكون نزيف اللثة مقلقًا؟','إذا استمر النزيف رغم التنظيف اليومي اللطيف، أو صاحبه تورم أو انزعاج، احجز موعدًا لدى طبيب الأسنان.']]},
  breath:{title:'ماذا أفعل للتخلص من رائحة الفم؟',tags:'رائحة الفم الكريهة الفم',replies:[['هل يساعد تنظيف اللسان؟','قد يساعد تنظيف اللسان بلطف على إزالة التراكمات. أفرّش مرتين يوميًا، ونظّف ما بين الأسنان، واشرب الماء بانتظام.'],['هل يمكن أن يكون جفاف الفم هو السبب؟','قد يساهم جفاف الفم في تغيّر رائحة النفس. إذا استمر الجفاف، اسأل طبيب الأسنان عن أسبابه المحتملة.'],['متى أستشير طبيب الأسنان؟','إذا استمرت رائحة الفم رغم المواظبة على التفريش والتنظيف، يمكن لطبيب الأسنان التحقق من الأسباب المحتملة.']]},
  whitening:{title:'هل تبييض الأسنان آمن للجميع؟',tags:'تبييض الأسنان آمن',replies:[['هل أجرّب منتجات تبييض الأسنان؟','لا يناسب التبييض الجميع، وقد يسبب حساسية مؤقتة. استشر طبيب الأسنان قبل البدء، خاصةً إذا كانت لديك حشوات أو حساسية.'],['هل يمكن أن يضر التبييض بأسناني؟','قد تسبب بعض المنتجات تهيج اللثة أو حساسية الأسنان. اتبع التعليمات واستشر طبيب الأسنان حول الخيارات المناسبة لك.'],['هل يبيّض المنتج التيجان أو الحشوات؟','قد لا يتغير لون التيجان أو الحشوات أو القشور مع منتجات التبييض. اسأل طبيب أسنانك عن النتائج المتوقعة.']]}
};
const blogAr=[{category:'العناية اليومية',time:'٥ دقائق',title:'عادات يومية بسيطة تصنع فرقًا كبيرًا',desc:'طريقة سهلة ولطيفة لبناء روتين تشكرك عليه ابتسامتك.'},{category:'صحة اللثة',time:'٤ دقائق',title:'لنتحدث عن صحة اللثة',desc:'ما الذي قد تخبرك به لثتك، وكيف تعتني بها أكثر.'},{category:'ملاحظات لابتسامتك',time:'٦ دقائق',title:'حقيقة أم خرافة؟ أسئلة عن ابتسامتك',desc:'نراجع بعض المعتقدات الشائعة مع منظور مهني.'}];
const t=(en,ar)=>currentLang==='ar'?ar:en;
const getFaqTitle=f=>currentLang==='ar'?(faqAr[f.id]?.title||f.titleAr||f.title):f.title;
const getReplies=f=>currentLang==='ar'?(faqAr[f.id]?.replies||f.repliesAr||f.replies):f.replies;
const questionGrid=document.querySelector('#questionGrid');
const search=document.querySelector('#faqSearch');
const searchWrap=document.querySelector('#searchWrap');
const results=document.querySelector('#faqResults');
const chatSection=document.querySelector('#chatSection');
const chatBody=document.querySelector('#chatBody');
const quickReplies=document.querySelector('#quickReplies');
let activeFaq=null;
let placeholderTimer=null;
let placeholderIndex=0;
let currentPlaceholder='';
function placeholderSuggestions(){return currentLang==='ar'?['كيف أخفف حساسية الأسنان؟','ما الطريقة الصحيحة لاستخدام الخيط؟','كم مرة أفرّش أسناني؟','لماذا تنزف اللثة؟']:['What causes tooth sensitivity?','How should I floss?','How often should I brush?','Why do gums bleed?']}
function startPlaceholderRotation(){window.clearTimeout(placeholderTimer);if(search.value||document.activeElement===search)return;const suggestions=placeholderSuggestions();placeholderIndex%=suggestions.length;currentPlaceholder=suggestions[placeholderIndex];let position=0;search.placeholder='';const typeNext=()=>{if(search.value||document.activeElement===search)return;position++;search.placeholder=currentPlaceholder.slice(0,position);if(position<currentPlaceholder.length)placeholderTimer=window.setTimeout(typeNext,65);else placeholderTimer=window.setTimeout(eraseNext,3000)};const eraseNext=()=>{if(search.value||document.activeElement===search)return;position--;search.placeholder=currentPlaceholder.slice(0,position);if(position>0)placeholderTimer=window.setTimeout(eraseNext,35);else{placeholderIndex=(placeholderIndex+1)%suggestions.length;placeholderTimer=window.setTimeout(startPlaceholderRotation,250)}};typeNext()}

function renderQuestions(){questionGrid.innerHTML=faqs.map(f=>`<button class="question-card" data-faq="${f.id}"><span class="q-card-top"><span class="q-arrow" aria-hidden="true"></span></span><strong>${getFaqTitle(f)}</strong></button>`).join('')}
function matches(q){const normalized=q.trim().toLowerCase();return normalized?faqs.filter(f=>(getFaqTitle(f)+' '+f.tags+' '+(faqAr[f.id]?.tags||'')).toLowerCase().includes(normalized)):faqs.slice(0,4)}
function renderResults(){const found=matches(search.value);results.innerHTML=`<div class="result-label">${t('SUGGESTED QUESTIONS','أسئلة مقترحة')}</div>`+(found.length?found.map(f=>`<button class="result-item" role="option" data-faq="${f.id}">${getFaqTitle(f)}</button>`).join(''):`<div class="no-results">${t('No exact match yet. Try a different search, or browse a question below.','لم نجد سؤالًا مطابقًا. جرّب كلمات أخرى أو اختر أحد الأسئلة أدناه.')}</div>`);search.setAttribute('aria-expanded','true')}
renderQuestions();
search.addEventListener('focus',()=>{window.clearTimeout(placeholderTimer);if(!search.value)search.placeholder=currentPlaceholder||placeholderSuggestions()[placeholderIndex%placeholderSuggestions().length];searchWrap.classList.add('open');renderResults()});search.addEventListener('input',renderResults);search.addEventListener('blur',()=>{if(!search.value)startPlaceholderRotation()});
document.addEventListener('click',e=>{if(!searchWrap.contains(e.target)){searchWrap.classList.remove('open');search.setAttribute('aria-expanded','false')}const button=e.target.closest('[data-faq]');if(button)openChat(button.dataset.faq)});
function renderReplies(){quickReplies.innerHTML=getReplies(activeFaq).map((r,i)=>`<button class="quick-reply" data-reply="${i}">${r[0]}</button>`).join('')}
const zoyMessageAvatar='<img class="message-avatar zoy-message-photo" src="images/ZOY.png" alt="ZOY" />';
function openChat(id){activeFaq=faqs.find(f=>f.id===id);if(!activeFaq)return;searchWrap.classList.remove('open');chatSection.hidden=false;chatBody.innerHTML=`<div class="message-row">${zoyMessageAvatar}<div class="message-bubble">${t(`Hi there! I’m ZOY. I’m here to help with <b>${activeFaq.title.toLowerCase()}</b>.<br><br>Pick a question below and we’ll take it one step at a time.`,`أهلًا بك! أنا زوي، أساعدك في موضوع <b>${getFaqTitle(activeFaq)}</b>.<br><br>اختر سؤالًا وسنتناوله معًا خطوة بخطوة.`)}</div><span class="message-time">${t('now','الآن')}</span></div>`;renderReplies();chatSection.scrollIntoView({behavior:'smooth',block:'center'})}
quickReplies.addEventListener('click',e=>{const button=e.target.closest('[data-reply]');if(!button||!activeFaq)return;const [question,answer]=getReplies(activeFaq)[Number(button.dataset.reply)];const userMessage=document.createElement('div');userMessage.className='message-row user';userMessage.innerHTML='<span class="message-time">'+t('now','الآن')+'</span><div class="message-bubble"></div>';userMessage.querySelector('.message-bubble').textContent=question;chatBody.appendChild(userMessage);const typing=document.createElement('div');typing.className='message-row';typing.innerHTML=zoyMessageAvatar+'<div class="message-bubble">'+t('One moment while I find that for you…','لحظة من فضلك، أبحث لك عن الإجابة…')+'</div>';chatBody.appendChild(typing);quickReplies.innerHTML='';chatBody.scrollTop=chatBody.scrollHeight;window.setTimeout(()=>{typing.remove();const response=document.createElement('div');response.className='message-row';const avatar=document.createElement('img');avatar.className='message-avatar zoy-message-photo';avatar.src='images/ZOY.png';avatar.alt='ZOY';const bubble=document.createElement('div');bubble.className='message-bubble';bubble.textContent=answer;response.append(avatar,bubble);chatBody.appendChild(response);chatBody.scrollTop=chatBody.scrollHeight;renderReplies()},650)});
document.querySelector('#backToQuestions').addEventListener('click',()=>{chatSection.hidden=true;document.querySelector('#popular').scrollIntoView({behavior:'smooth'})});document.querySelector('#closeChat').addEventListener('click',()=>{chatSection.hidden=true});
const flowerSvg='<svg viewBox="0 0 120 120" fill="none" aria-hidden="true"><g fill="#e5c2d5"><ellipse cx="60" cy="33" rx="12" ry="25"/><ellipse cx="60" cy="87" rx="12" ry="25"/><ellipse cx="33" cy="60" rx="25" ry="12"/><ellipse cx="87" cy="60" rx="25" ry="12"/><ellipse cx="41" cy="41" rx="12" ry="24" transform="rotate(-45 41 41)"/><ellipse cx="79" cy="79" rx="12" ry="24" transform="rotate(-45 79 79)"/><ellipse cx="79" cy="41" rx="12" ry="24" transform="rotate(45 79 41)"/><ellipse cx="41" cy="79" rx="12" ry="24" transform="rotate(45 41 79)"/></g><circle cx="60" cy="60" r="12" fill="#d5ad7e"/></svg>';
const toothSvg='<svg viewBox="0 0 120 120" fill="none" aria-hidden="true"><path d="M36 24c-12 1-19 10-18 25 1 13 7 22 11 37 3 12 7 21 13 20 7-1 5-24 18-24s11 23 18 24c6 1 10-8 13-20 4-15 10-24 11-37 1-15-6-24-18-25-9-1-16 5-24 5s-15-6-24-5Z" fill="#fff" stroke="#bea9d3" stroke-width="4"/><path d="M43 49c0 2-2 4-4 4s-4-2-4-4 2-4 4-4 4 2 4 4Zm42 0c0 2-2 4-4 4s-4-2-4-4 2-4 4-4 4 2 4 4Z" fill="#7e6b90"/><path d="M46 68c8 9 20 9 28 0" stroke="#d692a8" stroke-width="4" stroke-linecap="round"/></svg>';
const smileSvg='<svg viewBox="0 0 120 120" fill="none" aria-hidden="true"><circle cx="60" cy="60" r="36" fill="#fff"/><path d="M32 65c14 22 42 22 56 0" fill="#edbdc9" stroke="#9b7085" stroke-width="4" stroke-linecap="round"/><path d="M43 67v6m11-4v8m12-8v8m11-10v6" stroke="#fff" stroke-width="3" stroke-linecap="round"/><circle cx="45" cy="49" r="3" fill="#544658"/><circle cx="75" cy="49" r="3" fill="#544658"/></svg>';
function renderBlogs(){document.querySelector('#blogGrid').innerHTML=blogs.map((b,i)=>{const x=currentLang==='ar'?(blogAr[i]||{category:b.categoryAr||b.category,time:b.time,title:b.titleAr||b.title,desc:b.descAr||b.desc}):b;return `<article class="blog-card"><div class="blog-art ${b.palette||'lilac'}">${(b.art||'tooth')==='tooth'?toothSvg:(b.art||'tooth')==='flower'?flowerSvg:smileSvg}</div><div class="blog-body"><div class="blog-meta">${x.category} &nbsp;·&nbsp; ${x.time}</div><h3>${x.title}</h3><p>${x.desc}</p><button class="blog-read" type="button" data-blog-id="${b.id||''}">${t('Read the story','اقرأ المقال')}</button></div></article>`}).join('')}
renderBlogs();
document.querySelector('#blogGrid').addEventListener('click',e=>{const button=e.target.closest('.blog-read');if(!button)return;const article=blogs.find(b=>b.id===button.dataset.blogId);if(article){const ar=currentLang==='ar';document.querySelector('#articleMeta').textContent=ar?(article.categoryAr||article.category):article.category;document.querySelector('#articleTitle').textContent=ar?(article.titleAr||article.title):article.title;document.querySelector('#articleAuthor').textContent=ar?`بقلم ${article.authorAr||article.author}`:`By ${article.author}`;document.querySelector('#articleContent').textContent=ar?(article.bodyAr||article.body):article.body;document.querySelector('#articleDialog').showModal();return}const toast=document.querySelector('#toast');toast.textContent=currentLang==='ar'?'مقالات الأطباء قريبًا.':'Doctor articles are coming soon.';toast.classList.add('show');window.setTimeout(()=>toast.classList.remove('show'),2200)});
function renderPeople(){document.querySelector('#cofounders').innerHTML=cofounders.map(person=>`<div class="cofounder"><img class="cofounder-photo" src="contributors/${person.photo}" alt="${currentLang==='ar'?person.nameAr:person.name}" loading="lazy" /><strong>${currentLang==='ar'?person.nameAr:person.name}</strong></div>`).join('');document.querySelector('#contributors').innerHTML=people.map((person,i)=>`<div class="contributor"><img class="contrib-photo" src="contributors/${peoplePhotoFiles[i]}.png" alt="${currentLang==='ar'?peopleAr[i]:person}" loading="lazy" /><div><strong>${currentLang==='ar'?peopleAr[i]:person}</strong><span>Team contributor</span></div></div>`).join('')}
renderPeople();
const menu=document.querySelector('.menu-toggle');menu.addEventListener('click',()=>{const nav=document.querySelector('.nav-links');const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('mobile-open',open)});document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');document.querySelector('.nav-links').classList.remove('mobile-open')}));

function applyLanguage(){const ar=currentLang==='ar';document.documentElement.lang=ar?'ar':'en';document.documentElement.dir=ar?'rtl':'ltr';document.title=ar?'websitename — معلومات لصحة أسنانك':'websitename — Dental care, made clearer';document.querySelector('#languageToggle').textContent=ar?'English':'العربية';document.querySelector('#languageToggle').setAttribute('aria-label',ar?'Switch language to English':'تغيير اللغة إلى العربية');document.querySelector('.menu-toggle').setAttribute('aria-label',ar?'فتح القائمة':'Open menu');document.querySelector('#backToQuestions').textContent=t('Back','رجوع');document.querySelector('#backToQuestions').setAttribute('aria-label',t('Back to questions','العودة للأسئلة'));document.querySelector('#closeChat').textContent=t('Close','إغلاق');document.querySelector('#adminGateTitle').textContent=t('Admin access','دخول الإدارة');document.querySelector('#adminGateDescription').textContent=t('Enter the admin access number.','أدخل رقم دخول الإدارة.');document.querySelector('#adminCodeLabel').textContent=t('Access number','رقم الدخول');document.querySelector('#adminGateCancel').textContent=t('Cancel','إلغاء');document.querySelector('.admin-gate-submit').textContent=t('Continue','متابعة');
const set=(s,value)=>{const el=document.querySelector(s);if(el)el.innerHTML=value};
set('.nav-links',`<a href="#answers">${t('Find an answer','ابحث عن إجابة')}</a><a href="#journal">${t('The journal','المدونة')}</a><a href="#about">${t('About us','من نحن')}</a>`);
set('.top-cta',t('Let’s get you answers','لنعثر لك على إجابة'));
set('.hero h1',ar?'صحة فمك تبدأ<br /><span>بـإجابات واضحة.</span>':'Good oral health<br />starts with <span>good answers.</span>');
set('.hero-copy',t('A friendly place for the questions you’ve always had about your smile. Thoughtfully guided by dental professionals at BUE.','مساحة ودودة لإجابات أسئلتك عن ابتسامتك، بإرشاد أطباء ومتخصصين في طب الأسنان بالجامعة البريطانية في مصر.'));
document.querySelector('meta[name="description"]').content=t('Friendly, doctor-supported answers to your everyday dental hygiene questions.','إجابات ودودة عن أسئلتك اليومية حول صحة الأسنان، بإشراف أطباء ومتخصصين.');
set('.card-caption',ar?'ابتسامة صحية<br /><b>تليق بك.</b>':'A healthy smile<br /><b>looks good on you.</b>');set('.note-one',ar?'رعاية تبدأ<br />بحوار ودود':'Care that feels<br />like a conversation');set('.note-two',t('Reviewed with care','معلومات موثوقة بعناية'));
search.dir=ar?'rtl':'ltr';search.setAttribute('aria-label',t('Search dental questions','ابحث في أسئلة صحة الأسنان'));if(!search.value){const examples=placeholderSuggestions();currentPlaceholder=examples[placeholderIndex%examples.length];search.placeholder=currentPlaceholder;if(document.activeElement!==search)startPlaceholderRotation()}
set('.search-hint',t('Not sure where to start? Pick a question below.','لا تعرف من أين تبدأ؟ اختر سؤالًا أدناه.'));
set('.section-heading h2',t('What’s on your mind?','ما الذي يشغل بالك؟'));
set('.other-copy',`<strong>${t('Something else on your mind?','هل لديك سؤال آخر؟')}</strong><span>${t('Tell us what you’re wondering about.','أخبرنا بما تود معرفته.')}</span>`);set('.coming-soon',t('COMING SOON','قريبًا'));document.querySelector('.other-disabled').setAttribute('aria-label',t('Other questions coming soon','أسئلة أخرى — قريبًا'));
set('.trust-line',`${t('Made with care alongside dental professionals at','بالتعاون مع أطباء ومتخصصين في طب الأسنان بـ')} <strong>BUE</strong>`);
set('.compose-label',t('PICK A QUESTION TO GET STARTED','اختر سؤالًا لنبدأ'));set('.chat-footer',t('Friendly information, supported by dental professionals. For personal advice, please speak with your dentist.','معلومات إرشادية بالتعاون مع متخصصين. للحصول على نصيحة شخصية، يرجى استشارة طبيب الأسنان.'));
set('.journal-heading .soft-eyebrow',t('WEBSITENAME JOURNAL','مدونة WEBSITENAME'));set('.journal h2',ar?'مقالات قصيرة<br />لابتسامة أجمل.':'Little reads for<br />brighter smiles.');set('.all-articles',t('All articles','كل المقالات'));
set('.editorial-note p',`${t('Good advice comes from people who care.','النصيحة الجيدة تأتي ممن يهتمون بصحتك.')}<br /><b>${t('Every article is created with dental professionals at BUE.','كل مقال يُعد بالتعاون مع أطباء ومتخصصين في طب الأسنان بالجامعة البريطانية في مصر.')}</b>`);
set('.about-top .eyebrow',t('A SMILE IS A TEAM EFFORT',''));set('.about-top h2',ar?'تعرّف على فريق<br />صنع هذه <span>المبادرة.</span>':'Meet the people<br />behind the <span>care.</span>');set('.about-top p',t('We’re a team of BUE students working alongside dental professionals to make oral health information feel a little more human — and a lot easier to find.','نحن فريق من طلاب الجامعة البريطانية في مصر، نعمل مع أطباء ومتخصصين لنجعل معلومات صحة الفم أقرب إليك وأسهل في الوصول.'));document.querySelector('#cofoundersHeading').textContent=t('CO-FOUNDERS','المؤسسان');
set('.about-foot',`<span>${t('Made with care and a lot of curiosity.','صُنع بعناية وكثير من الشغف والفضول.')}</span><span>${t('THE BUE DENTAL HYGIENE PROJECT · 2026','مشروع صحة الأسنان بالجامعة البريطانية · ٢٠٢٦')}</span>`);
set('.footer>span',t('A softer place to start caring for your smile.','مساحة ودودة لتبدأ العناية بابتسامتك.'));set('.footer>a:last-child',t('Back to top','العودة إلى الأعلى'));
renderQuestions();renderBlogs();renderPeople();document.querySelectorAll('#contributors .contributor').forEach((el)=>{el.querySelector('span').textContent=ar?'مساهم في الفريق':'Team contributor'});if(searchWrap.classList.contains('open'))renderResults();}
document.querySelector('#languageToggle').addEventListener('click',()=>{currentLang=currentLang==='ar'?'en':'ar';applyLanguage()});document.querySelector('.nav-links').addEventListener('click',e=>{if(e.target.closest('a')){menu.setAttribute('aria-expanded','false');document.querySelector('.nav-links').classList.remove('mobile-open')}});applyLanguage();
document.querySelector('#adminAccess').addEventListener('click',()=>{document.querySelector('#adminGateError').textContent='';document.querySelector('#adminCode').value='';document.querySelector('#adminGate').showModal();document.querySelector('#adminCode').focus()});document.querySelector('#adminGateCancel').addEventListener('click',()=>document.querySelector('#adminGate').close());document.querySelector('#adminGateForm').addEventListener('submit',event=>{event.preventDefault();if(document.querySelector('#adminCode').value==='67'){sessionStorage.setItem('websitename-admin-access','1');window.location.href='admin.html'}else{document.querySelector('#adminGateError').textContent=currentLang==='ar'?'الرقم غير صحيح. حاول مرة أخرى.':'That number is not correct. Try again.';document.querySelector('#adminCode').select()}});
