import { supabase } from './supabase.js';
import zoyPhotoUrl from './images/ZOY.png';

const contributorPhotoUrls=import.meta.glob('./contributors/*.png',{eager:true,query:'?url',import:'default'});
const contributorPhotoUrl=filename=>contributorPhotoUrls[`./contributors/${filename}`]||`contributors/${filename}`;

const faqs=[];
const blogs=[
  {category:'EVERYDAY CARE',time:'5 MIN READ',title:'The tiny daily habits that make a big difference',desc:'A kinder, simpler approach to building a routine your smile will thank you for.',palette:'lilac',art:'tooth'},
  {category:'GUM HEALTH',time:'4 MIN READ',title:'Let’s talk about your gums',desc:'What your gums might be telling you, and how to give them a little extra care.',palette:'peach',art:'flower'},
  {category:'SMILE NOTES',time:'6 MIN READ',title:'Myth or fact: your smile edition',desc:'A few common dental beliefs, gently unpacked with a professional perspective.',palette:'rose',art:'smile'}
];
const people=['Dr. Ziad Mahmoud','Dr. Omar Sameh','Dr. Yehia Tarek','Dr. Tarek Mohammed','Dr. Shreef Mohammed','Dr. Ranim Elhusseiny','Dr. Sara Mohammad','Dr. Nada Waleed','Dr. Nadine Ahmed','Dr. Najah Abdelfattah','Eng. Mohamed Ahmed','Eng. Shady Mohamed'];
const peopleAr=['د. زياد محمود','د. عمر سامح','د. يحيى طارق','د. طارق محمد','د. شريف محمد','د. رنيم الحسيني','د. سارة محمد','د. ندى وليد','د. نادين أحمد','د. نجاح عبد الفتاح','م. محمد أحمد','م. شادي محمد'];
const peoplePhotoFiles=[1,2,3,4,6,10,7,8,9,11,12,13];
const webDeveloperIndex=people.indexOf('Eng. Mohamed Ahmed');
const aiEngineerIndex=people.indexOf('Eng. Shady Mohamed');
const cofounders=[{name:'Prof. Dalia Ghalwash',nameAr:'أ.د. داليا غلاوش',photo:'0.png'},{name:'Dr. Youssef Yasser',nameAr:'د. يوسف ياسر',photo:'5.png'}];
const savedLanguage=localStorage.getItem('siteLanguage');
let currentLang=savedLanguage==='en'?'en':'ar';
const blogAr=[{category:'العناية اليومية',time:'٥ دقائق',title:'عادات يومية بسيطة تصنع فرقًا كبيرًا',desc:'طريقة سهلة ولطيفة لبناء روتين تشكرك عليه ابتسامتك.'},{category:'صحة اللثة',time:'٤ دقائق',title:'لنتحدث عن صحة اللثة',desc:'ما الذي قد تخبرك به لثتك، وكيف تعتني بها أكثر.'},{category:'ملاحظات لابتسامتك',time:'٦ دقائق',title:'حقيقة أم خرافة؟ أسئلة عن ابتسامتك',desc:'نراجع بعض المعتقدات الشائعة مع منظور مهني.'}];
const t=(en,ar)=>currentLang==='ar'?ar:en;
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const getFaqTitle=f=>currentLang==='ar'?(f.titleAr||f.title):f.title;
const getReplies=f=>currentLang==='ar'?(f.repliesAr||f.replies):f.replies;
const questionGrid=document.querySelector('#questionGrid');
const search=document.querySelector('#faqSearch');
const searchWrap=document.querySelector('#searchWrap');
const results=document.querySelector('#faqResults');
const chatSection=document.querySelector('#chatSection');
const chatBody=document.querySelector('#chatBody');
const quickReplies=document.querySelector('#quickReplies');
let activeFaq=null;
let placeholderTimer=null;
let placeholderIndex=0;
let currentPlaceholder='';
function placeholderSuggestions(){return currentLang==='ar'?['كيف أخفف حساسية الأسنان؟','ما الطريقة الصحيحة لاستخدام الخيط؟','كم مرة أفرّش أسناني؟','لماذا تنزف اللثة؟']:['What causes tooth sensitivity?','How should I floss?','How often should I brush?','Why do gums bleed?']}
function startPlaceholderRotation(){window.clearTimeout(placeholderTimer);if(search.value||document.activeElement===search)return;const suggestions=placeholderSuggestions();placeholderIndex%=suggestions.length;currentPlaceholder=suggestions[placeholderIndex];let position=0;search.placeholder='';const typeNext=()=>{if(search.value||document.activeElement===search)return;position++;search.placeholder=currentPlaceholder.slice(0,position);if(position<currentPlaceholder.length)placeholderTimer=window.setTimeout(typeNext,65);else placeholderTimer=window.setTimeout(eraseNext,3000)};const eraseNext=()=>{if(search.value||document.activeElement===search)return;position--;search.placeholder=currentPlaceholder.slice(0,position);if(position>0)placeholderTimer=window.setTimeout(eraseNext,35);else{placeholderIndex=(placeholderIndex+1)%suggestions.length;placeholderTimer=window.setTimeout(startPlaceholderRotation,250)}};typeNext()}

function renderQuestions(){questionGrid.innerHTML=faqs.map(f=>`<button class="question-card" data-faq="${escapeHtml(f.id)}"><span class="q-card-top"><span class="q-arrow" aria-hidden="true"></span></span><strong>${escapeHtml(getFaqTitle(f))}</strong></button>`).join('')}
function matches(q){const normalized=q.trim().toLowerCase();return normalized?faqs.filter(f=>(getFaqTitle(f)+' '+(f.title||'')+' '+(f.tags||'')+' '+(f.tagsAr||'')).toLowerCase().includes(normalized)):faqs.slice(0,4)}
function renderResults(){const found=matches(search.value);results.innerHTML=`<div class="result-label">${t('SUGGESTED QUESTIONS','أسئلة مقترحة')}</div>`+(found.length?found.map(f=>`<button class="result-item" role="option" data-faq="${escapeHtml(f.id)}">${escapeHtml(getFaqTitle(f))}</button>`).join(''):`<div class="no-results">${t('No exact match yet. Try a different search, or browse a question below.','لم نجد سؤالًا مطابقًا. جرّب كلمات أخرى أو اختر أحد الأسئلة أدناه.')}</div>`);search.setAttribute('aria-expanded','true')}
renderQuestions();
search.addEventListener('focus',()=>{window.clearTimeout(placeholderTimer);if(!search.value)search.placeholder=currentPlaceholder||placeholderSuggestions()[placeholderIndex%placeholderSuggestions().length];searchWrap.classList.add('open');renderResults()});search.addEventListener('input',renderResults);search.addEventListener('blur',()=>{if(!search.value)startPlaceholderRotation()});
document.addEventListener('click',e=>{if(!searchWrap.contains(e.target)){searchWrap.classList.remove('open');search.setAttribute('aria-expanded','false')}const button=e.target.closest('[data-faq]');if(button)openChat(button.dataset.faq)});
function renderReplies(){quickReplies.innerHTML=getReplies(activeFaq).map((r,i)=>`<button class="quick-reply" data-reply="${i}">${escapeHtml(r[0])}</button>`).join('')}
const zoyMessageAvatar=`<img class="message-avatar zoy-message-photo" src="${zoyPhotoUrl}" alt="ZOY" />`;
function openChat(id){activeFaq=faqs.find(f=>f.id===id);if(!activeFaq)return;searchWrap.classList.remove('open');chatSection.hidden=false;chatBody.innerHTML=`<div class="message-row">${zoyMessageAvatar}<div class="message-bubble">${t(`Hi there! I’m ZOY. I’m here to help with <b>${escapeHtml(activeFaq.title.toLowerCase())}</b>.<br><br>Pick a question below and we’ll take it one step at a time.`,`أهلًا بك! أنا زوي، أساعدك في موضوع <b>${escapeHtml(getFaqTitle(activeFaq))}</b>.<br><br>اختر سؤالًا وسنتناوله معًا خطوة بخطوة.`)}</div><span class="message-time">${t('now','الآن')}</span></div>`;renderReplies();chatSection.scrollIntoView({behavior:'smooth',block:'center'})}
quickReplies.addEventListener('click',e=>{const button=e.target.closest('[data-reply]');if(!button||!activeFaq)return;const [question,answer]=getReplies(activeFaq)[Number(button.dataset.reply)];const userMessage=document.createElement('div');userMessage.className='message-row user';userMessage.innerHTML='<span class="message-time">'+t('now','الآن')+'</span><div class="message-bubble"></div>';userMessage.querySelector('.message-bubble').textContent=question;chatBody.appendChild(userMessage);const typing=document.createElement('div');typing.className='message-row';typing.innerHTML=zoyMessageAvatar+'<div class="message-bubble">'+t('One moment while I find that for you…','لحظة من فضلك، أبحث لك عن الإجابة…')+'</div>';chatBody.appendChild(typing);quickReplies.innerHTML='';chatBody.scrollTop=chatBody.scrollHeight;window.setTimeout(()=>{typing.remove();const response=document.createElement('div');response.className='message-row';const avatar=document.createElement('img');avatar.className='message-avatar zoy-message-photo';avatar.src=zoyPhotoUrl;avatar.alt='ZOY';const bubble=document.createElement('div');bubble.className='message-bubble';bubble.textContent=answer;response.append(avatar,bubble);chatBody.appendChild(response);chatBody.scrollTop=chatBody.scrollHeight;renderReplies()},650)});
document.querySelector('#backToQuestions').addEventListener('click',()=>{chatSection.hidden=true;document.querySelector('#popular').scrollIntoView({behavior:'smooth'})});document.querySelector('#closeChat').addEventListener('click',()=>{chatSection.hidden=true});
const flowerSvg='<svg viewBox="0 0 120 120" fill="none" aria-hidden="true"><g fill="#e5c2d5"><ellipse cx="60" cy="33" rx="12" ry="25"/><ellipse cx="60" cy="87" rx="12" ry="25"/><ellipse cx="33" cy="60" rx="25" ry="12"/><ellipse cx="87" cy="60" rx="25" ry="12"/><ellipse cx="41" cy="41" rx="12" ry="24" transform="rotate(-45 41 41)"/><ellipse cx="79" cy="79" rx="12" ry="24" transform="rotate(-45 79 79)"/><ellipse cx="79" cy="41" rx="12" ry="24" transform="rotate(45 79 41)"/><ellipse cx="41" cy="79" rx="12" ry="24" transform="rotate(45 41 79)"/></g><circle cx="60" cy="60" r="12" fill="#d5ad7e"/></svg>';
const toothSvg='<svg viewBox="0 0 120 120" fill="none" aria-hidden="true"><path d="M36 24c-12 1-19 10-18 25 1 13 7 22 11 37 3 12 7 21 13 20 7-1 5-24 18-24s11 23 18 24c6 1 10-8 13-20 4-15 10-24 11-37 1-15-6-24-18-25-9-1-16 5-24 5s-15-6-24-5Z" fill="#fff" stroke="#bea9d3" stroke-width="4"/><path d="M43 49c0 2-2 4-4 4s-4-2-4-4 2-4 4-4 4 2 4 4Zm42 0c0 2-2 4-4 4s-4-2-4-4 2-4 4-4 4 2 4 4Z" fill="#7e6b90"/><path d="M46 68c8 9 20 9 28 0" stroke="#d692a8" stroke-width="4" stroke-linecap="round"/></svg>';
const smileSvg='<svg viewBox="0 0 120 120" fill="none" aria-hidden="true"><circle cx="60" cy="60" r="36" fill="#fff"/><path d="M32 65c14 22 42 22 56 0" fill="#edbdc9" stroke="#9b7085" stroke-width="4" stroke-linecap="round"/><path d="M43 67v6m11-4v8m12-8v8m11-10v6" stroke="#fff" stroke-width="3" stroke-linecap="round"/><circle cx="45" cy="49" r="3" fill="#544658"/><circle cx="75" cy="49" r="3" fill="#544658"/></svg>';
function renderBlogs(){document.querySelector('#blogGrid').innerHTML=blogs.map((b,i)=>{const x=currentLang==='ar'?(b.remote?{category:b.categoryAr,time:b.time,title:b.titleAr,desc:b.descAr}:(blogAr[i]||{category:b.categoryAr||b.category,time:b.time,title:b.titleAr||b.title,desc:b.descAr||b.desc})):b;return `<article class="blog-card"><div class="blog-art ${b.palette||'lilac'}">${(b.art||'tooth')==='tooth'?toothSvg:(b.art||'tooth')==='flower'?flowerSvg:smileSvg}</div><div class="blog-body"><div class="blog-meta">${escapeHtml(x.category)} &nbsp;·&nbsp; ${escapeHtml(x.time)}</div><h3>${escapeHtml(x.title)}</h3><p>${escapeHtml(x.desc)}</p><button class="blog-read" type="button" data-blog-id="${escapeHtml(b.id||'')}">${t('Read the story','اقرأ المقال')}</button></div></article>`}).join('')}
renderBlogs();
document.querySelector('#blogGrid').addEventListener('click',e=>{const button=e.target.closest('.blog-read');if(!button)return;const article=blogs.find(b=>b.id===button.dataset.blogId);if(article){const ar=currentLang==='ar';document.querySelector('#articleMeta').textContent=ar?(article.categoryAr||article.category):article.category;document.querySelector('#articleTitle').textContent=ar?(article.titleAr||article.title):article.title;document.querySelector('#articleAuthor').textContent=ar?`بقلم ${article.authorAr||article.author}`:`By ${article.author}`;document.querySelector('#articleContent').textContent=ar?(article.bodyAr||article.body):article.body;document.querySelector('#articleDialog').showModal();return}const toast=document.querySelector('#toast');toast.textContent=currentLang==='ar'?'مقالات الأطباء قريبًا.':'Doctor articles are coming soon.';toast.classList.add('show');window.setTimeout(()=>toast.classList.remove('show'),2200)});
function renderPeople(){document.querySelector('#cofounders').innerHTML=cofounders.map(person=>`<div class="cofounder"><img class="cofounder-photo" src="${contributorPhotoUrl(person.photo)}" alt="${currentLang==='ar'?person.nameAr:person.name}" loading="lazy" /><strong>${currentLang==='ar'?person.nameAr:person.name}</strong></div>`).join('');document.querySelector('#contributors').innerHTML=people.map((person,i)=>`<div class="contributor"><img class="contrib-photo" src="${contributorPhotoUrl(`${peoplePhotoFiles[i]}.png`)}" alt="${currentLang==='ar'?peopleAr[i]:person}" loading="lazy" /><div><strong>${currentLang==='ar'?peopleAr[i]:person}</strong><span>${i===webDeveloperIndex?(currentLang==='ar'?'مطور ويب':'Web developer'):i===aiEngineerIndex?(currentLang==='ar'?'مهندس ذكاء اصطناعي':'AI engineer'):(currentLang==='ar'?'مساهم في الفريق':'Team contributor')}</span></div></div>`).join('')}
renderPeople();
async function loadPublishedContent(){
  const [faqResult,blogResult]=await Promise.all([
    supabase.from('faqs').select('id,question_en,question_ar,keywords_en,keywords_ar,replies,status').eq('status','published').order('created_at',{ascending:true}),
    supabase.from('blogs').select('id,title_en,title_ar,category_en,category_ar,author_en,author_ar,excerpt_en,excerpt_ar,body_en,body_ar,read_time,cover_image_url,status').eq('status','published').order('created_at',{ascending:true})
  ]);
  if(faqResult.error)throw faqResult.error;
  if(blogResult.error)throw blogResult.error;
  faqs.push(...faqResult.data.map(row=>({id:row.id,title:row.question_en,titleAr:row.question_ar,tags:(row.keywords_en||[]).join(' '),tagsAr:(row.keywords_ar||[]).join(' '),replies:(row.replies||[]).map(item=>[item.prompt_en,item.answer_en]),repliesAr:(row.replies||[]).map(item=>[item.prompt_ar,item.answer_ar]),tint:'#eee6f8',color:'#9675ba'})));
  blogs.push(...blogResult.data.map(row=>({id:row.id,remote:true,title:row.title_en,titleAr:row.title_ar,category:row.category_en,categoryAr:row.category_ar,author:row.author_en,authorAr:row.author_ar,desc:row.excerpt_en,descAr:row.excerpt_ar,body:row.body_en,bodyAr:row.body_ar,time:row.read_time||'5 MIN READ',imageUrl:row.cover_image_url,palette:'lilac',art:'tooth'})));
  applyLanguage();
}
loadPublishedContent().catch(error=>{console.error('Could not load published content from Supabase:',error);const toast=document.querySelector('#toast');toast.textContent=currentLang==='ar'?'تعذّر تحميل المحتوى المنشور من قاعدة البيانات.':'Could not load published content from the database.';toast.classList.add('show');window.setTimeout(()=>toast.classList.remove('show'),4500)});
const menu=document.querySelector('.menu-toggle');const nav=document.querySelector('.nav-links');let menuCloseTimer=null;function openMobileMenu(){window.clearTimeout(menuCloseTimer);nav.classList.remove('mobile-closing');nav.classList.add('mobile-open');menu.setAttribute('aria-expanded','true')}function closeMobileMenu(){if(!nav.classList.contains('mobile-open'))return;nav.classList.remove('mobile-open');menu.setAttribute('aria-expanded','false');if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){nav.classList.remove('mobile-closing');return}nav.classList.add('mobile-closing');window.clearTimeout(menuCloseTimer);menuCloseTimer=window.setTimeout(()=>nav.classList.remove('mobile-closing'),560)}menu.addEventListener('click',()=>{if(menu.getAttribute('aria-expanded')==='true')closeMobileMenu();else openMobileMenu()});

function applyLanguage(){const ar=currentLang==='ar';document.documentElement.lang=ar?'ar':'en';document.documentElement.dir=ar?'rtl':'ltr';document.title=ar?'websitename — معلومات لصحة أسنانك':'websitename — Dental care, made clearer';document.querySelector('#languageToggle').textContent=ar?'English':'العربية';document.querySelector('#languageToggle').setAttribute('aria-label',ar?'Switch language to English':'تغيير اللغة إلى العربية');document.querySelector('.menu-toggle').setAttribute('aria-label',ar?'فتح القائمة':'Open menu');document.querySelector('#backToQuestions').textContent=t('Back','رجوع');document.querySelector('#backToQuestions').setAttribute('aria-label',t('Back to questions','العودة للأسئلة'));document.querySelector('#closeChat').textContent=t('Close','إغلاق');document.querySelector('#adminGateTitle').textContent=t('Admin access','دخول الإدارة');document.querySelector('#adminGateDescription').textContent=t('Enter the admin access number.','أدخل رقم دخول الإدارة.');document.querySelector('#adminCodeLabel').textContent=t('Access number','رقم الدخول');document.querySelector('#adminGateCancel').textContent=t('Cancel','إلغاء');document.querySelector('.admin-gate-submit').textContent=t('Continue','متابعة');
const set=(s,value)=>{const el=document.querySelector(s);if(el)el.innerHTML=value};
set('.nav-links',`<a href="#answers">${t('Find an answer','ابحث عن إجابة')}</a><a href="#journal">${t('The journal','المدونة')}</a><a href="#about">${t('About us','من نحن')}</a>`);
set('.top-cta',t('Let’s get you answers','لنعثر لك على إجابة'));
set('.hero h1',ar?'صحة فمك تبدأ<br /><span>بـإجابات واضحة.</span>':'Good oral health<br />starts with <span>good answers.</span>');
set('.hero-copy',t('A friendly place for the questions you’ve always had about your smile. Thoughtfully guided by dental professionals at BUE.','مساحة ودودة لإجابات أسئلتك عن ابتسامتك، بإرشاد أطباء ومتخصصين في طب الأسنان بالجامعة البريطانية في مصر.'));
document.querySelector('meta[name="description"]').content=t('Friendly, doctor-supported answers to your everyday dental hygiene questions.','إجابات ودودة عن أسئلتك اليومية حول صحة الأسنان، بإشراف أطباء ومتخصصين.');
set('.card-caption',ar?'ابتسامة صحية<br /><b>تليق بك.</b>':'A healthy smile<br /><b>looks good on you.</b>');set('.note-one',ar?'رعاية تبدأ<br />بحوار ودود':'Care that feels<br />like a conversation');set('.note-two',t('Reviewed with care','معلومات موثوقة بعناية'));
search.dir=ar?'rtl':'ltr';search.setAttribute('aria-label',t('Search dental questions','ابحث في أسئلة صحة الأسنان'));if(!search.value){const examples=placeholderSuggestions();currentPlaceholder=examples[placeholderIndex%examples.length];search.placeholder=currentPlaceholder;if(document.activeElement!==search)startPlaceholderRotation()}
set('.search-hint',t('Not sure where to start? Pick a question below.','لا تعرف من أين تبدأ؟ اختر سؤالًا أدناه.'));
set('.section-heading h2',t('What’s on your mind?','ما الذي يشغل بالك؟'));
set('.other-copy',`<strong>${t('Something else on your mind?','هل لديك سؤال آخر؟')}</strong><span>${t('Tell us what you’re wondering about.','أخبرنا بما تود معرفته.')}</span>`);set('.coming-soon',t('COMING SOON','قريبًا'));document.querySelector('.other-disabled').setAttribute('aria-label',t('Other questions coming soon','أسئلة أخرى — قريبًا'));
set('.trust-line',`${t('Made with care alongside dental professionals at','بالتعاون مع أطباء ومتخصصين في طب الأسنان بـ')} <strong>BUE</strong>`);
set('.compose-label',t('PICK A QUESTION TO GET STARTED','اختر سؤالًا لنبدأ'));set('.chat-footer',t('Friendly information, supported by dental professionals. For personal advice, please speak with your dentist.','معلومات إرشادية بالتعاون مع متخصصين. للحصول على نصيحة شخصية، يرجى استشارة طبيب الأسنان.'));
set('.journal-heading .soft-eyebrow',t('WEBSITENAME JOURNAL','مدونة WEBSITENAME'));set('.journal h2',ar?'مقالات قصيرة<br />لابتسامة أجمل.':'Little reads for<br />brighter smiles.');set('.all-articles',t('All articles','كل المقالات'));
set('.editorial-note p',`${t('Good advice comes from people who care.','النصيحة الجيدة تأتي ممن يهتمون بصحتك.')}<br /><b>${t('Every article is created with dental professionals at BUE.','كل مقال يُعد بالتعاون مع أطباء ومتخصصين في طب الأسنان بالجامعة البريطانية في مصر.')}</b>`);
set('.about-top .eyebrow',t('A SMILE IS A TEAM EFFORT',''));set('.about-top h2',ar?'تعرّف على فريق<br />صنع هذه <span>المبادرة.</span>':'Meet the people<br />behind the <span>care.</span>');set('.about-top p',t('We’re a team of BUE students working alongside dental professionals to make oral health information feel a little more human — and a lot easier to find.','نحن فريق من طلاب الجامعة البريطانية في مصر، نعمل مع أطباء ومتخصصين لنجعل معلومات صحة الفم أقرب إليك وأسهل في الوصول.'));document.querySelector('#cofoundersHeading').textContent=t('CO-FOUNDERS','المؤسسان');
set('.about-foot',`<span>${t('Made with care and a lot of curiosity.','صُنع بعناية وكثير من الشغف والفضول.')}</span><span>${t('THE BUE DENTAL HYGIENE PROJECT · 2026','مشروع صحة الأسنان بالجامعة البريطانية · ٢٠٢٦')}</span>`);
set('.footer>span',t('A softer place to start caring for your smile.','مساحة ودودة لتبدأ العناية بابتسامتك.'));set('.footer>a:last-child',t('Back to top','العودة إلى الأعلى'));
renderQuestions();renderBlogs();renderPeople();if(searchWrap.classList.contains('open'))renderResults();}
document.querySelector('#languageToggle').addEventListener('click',()=>{currentLang=currentLang==='ar'?'en':'ar';localStorage.setItem('siteLanguage',currentLang);window.currentLanguage=currentLang;applyLanguage()});document.querySelector('.nav-links').addEventListener('click',e=>{if(e.target.closest('a'))closeMobileMenu()});window.currentLanguage=currentLang;applyLanguage();
document.querySelector('#adminAccess').addEventListener('click',()=>{window.location.href='admin.html'});
